### PR TITLE
unify webpack config into one file and use NODE_ENV to switch settings

### PR DESCRIPTION
**Pull request by Fedelaus**
You can add further properties to `environments` for UAT/Staging/etc

### CODE REVIEW

**Review by voodoods — CHANGES_REQUESTED** [review]
Just the file separation I'd like to keep. Everything else looks good! 👌

**Comment by Fedelaus** [comment]
@voodoods so reinstate the `production.config.ts` and `development.config.ts` and instead load the configuration from there?

**Comment by Fedelaus** [comment]
Just seen the second comment. No worries - I'll submit that in one second.

**Comment by Fedelaus** [comment]
@voodoods I've addressed your comment and reinstated the separate files.

**Review by voodoods — APPROVED** [review]
Looks good 👍 Thanks for the hint regarding the hacktoberfest label, I added it on the done PRs including this 👍 Thank you again for contributing!

**Pull request merged**
